#!/bin/bash

read -p 'WARNING: All data will be LOST! type: "yes",  [no]:' A
A=${A:-no}

if [ "$A" = "yes" ] ; then
   read -p 'Mysql root:' PW
   read -p 'DB name[mpbx]:' DB
   DB=${DB:-mpbx}
   echo " Install DB:" 
   [ ! -f "${DB}.sql" ] && echo "Error: DB ${DB}.sql NOT FOUND!" && exit || echo "  Install ${DB}.sql ... "
  ## cat "${DB}.sql" |  mysql -u root -p$PW $DB
  ## echo -e  "\n\n\t $DB loaded!  \n\n" 

   for type in func triggers ; do
    echo -e "\n Install $type :"
    for S in `ls ./${type}_*.sql`
     do 
       echo "     Installing $S ... "       
       cat $S | mysql -u root -p${PW} ${DB}
     done
   done
   echo -e "\n\n Done!"
fi
