#!/bin/bash

read -p 'WARNING: All data will be LOST! type: "yes",  [no]:' A
A=${A:-no}
## Extract Data only: mysqldump mpbx -u root -p -t --skip-triggers --compact --no-create-info  > mpbx-initial-data.sql
## Extract Structure only:  mysqldump mpbx -u root -p --no-data > mpbx.sql

if [ "$A" = "yes" ] ; then
   read -p 'Mysql root:' PW
   read -p 'DB name[mpbx]:' DB
   DB=${DB:-mpbx}
   echo " Install DB:" 
   echo -e  "\n\n\t $DB loaded!  \n\n" 

   for type in func triggers ; do
    echo -e "\n Install $type :"
    for S in `ls ./${type}_*.sql`
     do 
       echo "     Installing $S ... "       
       cat $S | mysql -u root -p${PW} ${DB}
     done
   done
   echo -e "\n\n Done!"
fi
