update mtree set name = 'Облако АТС' where name = 'Current Tenant PBX';
update mtree set name = 'IP Телефоны' where name = 'Extensions';
update mtree set name = 'Входящие Номера' where name = 'Inbound DIDs';
update mtree set name = 'Исходящие маршруты' where name = 'Outbound Routes';
update mtree set name = 'Облачные АТС' where name = 'Tenants';
update mtree set name = 'VOIP Транки' where name = 'Trunks';
update mtree set name = 'Номера DID' where name = 'DIDs';
update mtree set name = 'Голосовые меню' where name = 'Auto Attendant';
update mtree set name = 'Музыка удержания(MOH)' where name = 'MOH Profiles';
update mtree set name = 'Музыка на удержании' where name = 'Default Music-on-Hold';
update mtree set name = 'Голосовые записи' where name = 'Default Recordings';
update mtree set name = 'Медиа' where name = 'Media';
update mtree set name = 'Голосовые записи' where name = 'Recordings';
update mtree set name = 'Группы дозвона' where name = 'Ring Groups';
update mtree set name = 'Рабочие Смены операторов' where name = 'Shifts';
update mtree set name = 'Очереди звонков' where name = 'Queues';
update mtree set name = 'Конференции' where name = 'Conferences';
update mtree set name = 'Функциональные коды' where name = 'Feature Codes';
update mtree set name = 'Общие Настройкиа' where name = 'Tenant Defaults';
update mtree set name = 'Функции CallCenter' where name = 'Call Center Functions';
update mtree set name = 'Записи разговоров' where name = 'Call Recordings';
update mtree set name = 'Обзвон номеров' where name = 'Predictive Dialer';
update mtree set name = 'Учетные записи' where name = 'Administrators';
update mtree set name = 'История звонков' where name = 'CDRs';
update mtree set name = 'Статус-Монитор' where name = 'Dashboard';
update mtree set name = 'Отчёт о пропущенных' where name = 'Lost Calls Report';
update mtree set name = 'Заблокированные IP' where name = 'Black List IP';
update mtree set name = 'Отчеты' where name = 'Reports';
update mtree set name = 'Сводные отчеты операторов' where name = 'Summary reports';
update mtree set name = 'Состояние Телефонов' where name = 'User Status';
update mtree set name = 'Статистика входящих линий' where name = 'DID usage stats';
